#!/bin/bash

getVolume=$(pactl get-sink-volume $(pactl get-default-sink))

if [[ $# != 1 ]]
then
    echo "Usage: volume-get -p"
    exit 1
elif [[ $1 == "-p" ]]
then
    rmBeg=$(sed 's/Volume: front-left: [0-9]* \/  //' <<< $getVolume)
    percent=$(sed 's/ .*//' <<< $rmBeg)

    echo $percent
fi
